// This file is the authoring entry point for the schema: edit here first,
// run `bun run db:generate` to derive correct DDL into `./drizzle` (diffed
// against drizzle/meta/, not introspected), hand-add whatever the DSL can't
// express (RLS policies, grants, security-definer functions, data
// backfills), then `bun run db:migrate` to apply. `./drizzle` is the
// applied migration history. See drizzle/README.md and drizzle.config.ts's
// header.
//
// Every timestamp on an application table is `mode: 'string'`: this
// codebase passes timestamps around as ISO strings end to end (types/
// index.ts, the JSON API responses, ~62 `new Date(row.created_at)` call
// sites). lib/db/client.ts reinstates the postgres.js parsers that produce
// them. The four Better Auth tables are the exception — see their note.
//
// Never generated by `drizzle-kit pull` — pull hangs on this schema due to
// an upstream bug where drizzle-kit misclassifies foreign keys as check
// constraints during introspection
// (https://github.com/drizzle-team/drizzle-orm/issues/4496), unfixed as of
// drizzle-kit 0.31.10. `push` hits the same bug. Only `generate`/`migrate`
// are used against this config.
//
// If ever reconciling this file against a live database by hand, a table
// listing alone is NOT enough — it omits FK delete rules and indexes.
// Cross-check those against `pg_constraint.confdeltype` and `pg_indexes`
// directly, or cascades and indexes silently go missing (as they did once
// already).
import { sql } from 'drizzle-orm'
import {
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  smallint,
  text,
  time,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'

// --- Better Auth ---------------------------------------------------------
// These four tables are Better Auth's own storage, owned by us rather than
// by an external auth service (they replaced Supabase's `auth` schema).
// Better Auth resolves each field by its *Drizzle property name*, and the
// camelCase names below are exactly the names it expects — which is why
// lib/auth/index.ts overrides `modelName` only and carries no `fields` maps.
// Renaming a property here therefore breaks the adapter at runtime ("field
// does not exist in the schema") with nothing failing at compile time; these
// four tables are the only ones where the property name is load-bearing
// beyond TypeScript.
//
// `id` is `uuid` rather than Better Auth's default `text` so the twelve
// existing FK columns still typecheck; `advanced.database.generateId` is set
// to crypto.randomUUID() to match. Timestamps deliberately keep Drizzle's
// default `mode: 'date'` — Better Auth reads and writes real Date objects
// (it compares `expires_at` against now) — unlike the application tables
// below, which are `mode: 'string'`.
export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    token: text('token').notNull().unique(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  // The user_id index also backs the "last signed in" lookup on
  // /staff/students/[id], which reads max(created_at) per user.
  (t) => [index('sessions_user_id_idx').on(t.userId)]
)

export const accounts = pgTable(
  'accounts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    issuer: text('issuer').notNull(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex('accounts_issuer_account_id_uidx').on(t.issuer, t.accountId),
    index('accounts_user_id_idx').on(t.userId),
  ]
)

export const verifications = pgTable(
  'verifications',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index('verifications_identifier_idx').on(t.identifier)]
)

// --- Application tables ---------------------------------------------------

export const classes = pgTable('classes', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
})

export const classMembers = pgTable(
  'class_members',
  {
    classId: uuid('class_id').notNull().references(() => classes.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    role: text('role').default('student').notNull(),
    joinedAt: timestamp('joined_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.classId, t.userId] }),
    check('class_members_role_check', sql`${t.role} = ANY (ARRAY['student', 'teacher'])`),
    index('class_members_user_id_idx').on(t.userId),
  ]
)

export const classSchedules = pgTable(
  'class_schedules',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    classId: uuid('class_id').notNull().references(() => classes.id, { onDelete: 'cascade' }),
    dayOfWeek: smallint('day_of_week').notNull(),
    startTime: time('start_time').notNull(),
    durationMin: smallint('duration_min').default(60).notNull(),
    label: text('label'),
  },
  (t) => [check('class_schedules_day_of_week_check', sql`${t.dayOfWeek} >= 0 AND ${t.dayOfWeek} <= 6`)]
)

// Presence of a row = that lesson week is OPEN for that class; absence =
// locked.
export const classEnabledLessons = pgTable(
  'class_enabled_lessons',
  {
    classId: uuid('class_id').notNull().references(() => classes.id, { onDelete: 'cascade' }),
    lessonId: smallint('lesson_id').notNull(),
    enabledBy: uuid('enabled_by').references(() => users.id, { onDelete: 'set null' }),
    enabledAt: timestamp('enabled_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.classId, t.lessonId] }),
    check('class_enabled_lessons_lesson_id_check', sql`${t.lessonId} > 0`),
  ]
)

export const projects = pgTable(
  'projects',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    title: text('title').default('Untitled').notNull(),
    files: jsonb('files').default({}).notNull(),
    // notNull to match `Project` in types/index.ts, which declares all three
    // non-null and which every consumer relies on. They carry defaults and no
    // writer has ever left them unset, but the columns allowed NULL until the
    // Drizzle conversion made the mismatch a type error rather than an `any`.
    isPublic: boolean('is_public').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    lessonId: integer('lesson_id'),
    submissionStatus: text('submission_status'),
    lessonVersion: integer('lesson_version'),
  },
  (t) => [
    check(
      'projects_submission_status_check',
      sql`${t.submissionStatus} = ANY (ARRAY['submitted', 'approved', 'needs_work'])`
    ),
    index('projects_user_id_idx').on(t.userId),
  ]
)

export const messages = pgTable(
  'messages',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    role: text('role').notNull(),
    content: text('content').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (t) => [
    check('messages_role_check', sql`${t.role} = ANY (ARRAY['user', 'assistant', 'teacher'])`),
    index('messages_project_id_created_at_idx').on(t.projectId, t.createdAt),
  ]
)

export const prompts = pgTable(
  'prompts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').references(() => projects.id),
    content: text('content').notNull(),
    // notNull for the same reason as projects above: the prompt log is ordered
    // by this column, and a NULL would sort unpredictably.
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (t) => [index('prompts_user_id_created_at_idx').on(t.userId, t.createdAt)]
)

export const lessonProgress = pgTable(
  'lesson_progress',
  {
    projectId: uuid('project_id').primaryKey().references(() => projects.id, { onDelete: 'cascade' }),
    completedTaskIds: text('completed_task_ids').array().default([]).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (t) => [index('lesson_progress_updated_at_idx').on(t.updatedAt.desc())]
)

export const invoices = pgTable(
  'invoices',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    amountCents: integer('amount_cents').notNull(),
    description: text('description').notNull(),
    dueDate: date('due_date', { mode: 'string' }).notNull(),
    status: text('status').default('unpaid').notNull(),
    sentAt: timestamp('sent_at', { withTimezone: true, mode: 'string' }),
    paidAt: timestamp('paid_at', { withTimezone: true, mode: 'string' }),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (t) => [
    check('invoices_amount_cents_check', sql`${t.amountCents} > 0`),
    check('invoices_status_check', sql`${t.status} = ANY (ARRAY['unpaid', 'paid', 'void'])`),
  ]
)

// invoice_id/user_id are intentionally not cascaded — a receipt is an
// immutable snapshot that must outlive the invoice or user that created it.
export const receipts = pgTable('receipts', {
  id: uuid('id').defaultRandom().primaryKey(),
  invoiceId: uuid('invoice_id').notNull().references(() => invoices.id),
  userId: uuid('user_id').notNull().references(() => users.id),
  amountCents: integer('amount_cents').notNull(),
  description: text('description').notNull(),
  paidAt: timestamp('paid_at', { withTimezone: true, mode: 'string' }).notNull(),
  receiptNumber: text('receipt_number').notNull().unique(),
})

export const studentProfiles = pgTable('student_profiles', {
  userId: uuid('user_id').primaryKey().references(() => users.id, { onDelete: 'cascade' }),
  fullName: text('full_name').default('').notNull(),
  parentEmail: text('parent_email'),
  parentTelegramChatId: text('parent_telegram_chat_id'),
  notes: text('notes'),
  isActive: boolean('is_active').default(true).notNull(),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
})

export const userBuildMode = pgTable('user_build_mode', {
  userId: uuid('user_id').primaryKey().references(() => users.id, { onDelete: 'cascade' }),
  enabled: boolean('enabled').default(false).notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
})

export const appSettings = pgTable('app_settings', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
})

export const roles = pgTable('roles', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull().unique(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
})

export const permissions = pgTable('permissions', {
  id: uuid('id').defaultRandom().primaryKey(),
  key: text('key').notNull().unique(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
})

export const rolePermissions = pgTable(
  'role_permissions',
  {
    roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'cascade' }),
    permissionId: uuid('permission_id').notNull().references(() => permissions.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.roleId, t.permissionId] }), index('role_permissions_role_id_idx').on(t.roleId)]
)

// user_id/granted_by are NO ACTION in the DB (unlike most user_id FKs
// elsewhere, which cascade) — mirrored as-is, not "fixed" here.
export const userRoles = pgTable(
  'user_roles',
  {
    userId: uuid('user_id').notNull().references(() => users.id),
    roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'cascade' }),
    grantedBy: uuid('granted_by').references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.roleId] }), index('user_roles_user_id_idx').on(t.userId)]
)
