// Hand-authored from a live introspection of the Supabase Postgres schema
// (`mcp__supabase__list_tables`), not generated by `drizzle-kit pull` —
// pull crashes on this schema due to an upstream bug where drizzle-kit
// misclassifies foreign keys as check constraints during introspection
// (https://github.com/drizzle-team/drizzle-orm/issues/4496), unfixed as of
// drizzle-kit 0.31.10. Revisit `bun run db:pull` once that's resolved.
//
// supabase/migrations/*.sql remains the schema source of truth — update
// there first, apply the migration, then update this file to match.
import { sql } from 'drizzle-orm'
import {
  boolean,
  check,
  date,
  integer,
  jsonb,
  pgSchema,
  pgTable,
  primaryKey,
  smallint,
  text,
  time,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

// auth.users is managed by Supabase Auth, not our migrations — declared
// here only so FK columns below can reference it for type-safety.
const authSchema = pgSchema('auth')
export const authUsers = authSchema.table('users', {
  id: uuid('id').primaryKey(),
})

export const classes = pgTable('classes', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})

export const classMembers = pgTable(
  'class_members',
  {
    classId: uuid('class_id').notNull().references(() => classes.id),
    userId: uuid('user_id').notNull().references(() => authUsers.id),
    role: text('role').default('student').notNull(),
    joinedAt: timestamp('joined_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.classId, t.userId] }),
    check('class_members_role_check', sql`${t.role} = ANY (ARRAY['student', 'teacher'])`),
  ]
)

export const classSchedules = pgTable(
  'class_schedules',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    classId: uuid('class_id').notNull().references(() => classes.id),
    dayOfWeek: smallint('day_of_week').notNull(),
    startTime: time('start_time').notNull(),
    durationMin: smallint('duration_min').default(60).notNull(),
    label: text('label'),
  },
  (t) => [check('class_schedules_day_of_week_check', sql`${t.dayOfWeek} >= 0 AND ${t.dayOfWeek} <= 6`)]
)

// Presence of a row = that lesson week is OPEN for that class; absence =
// locked (see supabase/migrations/20260807180000_class_enabled_lessons.sql).
export const classEnabledLessons = pgTable(
  'class_enabled_lessons',
  {
    classId: uuid('class_id').notNull().references(() => classes.id),
    lessonId: smallint('lesson_id').notNull(),
    enabledBy: uuid('enabled_by').references(() => authUsers.id),
    enabledAt: timestamp('enabled_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.classId, t.lessonId] }),
    check('class_enabled_lessons_lesson_id_check', sql`${t.lessonId} > 0`),
  ]
)

export const projects = pgTable(
  'projects',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id').notNull().references(() => authUsers.id),
    title: text('title').default('Untitled').notNull(),
    files: jsonb('files').default({}).notNull(),
    isPublic: boolean('is_public').default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    lessonId: integer('lesson_id'),
    submissionStatus: text('submission_status'),
    lessonVersion: integer('lesson_version'),
  },
  (t) => [
    check(
      'projects_submission_status_check',
      sql`${t.submissionStatus} = ANY (ARRAY['submitted', 'approved', 'needs_work'])`
    ),
  ]
)

export const messages = pgTable(
  'messages',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    projectId: uuid('project_id').notNull().references(() => projects.id),
    userId: uuid('user_id').notNull().references(() => authUsers.id),
    role: text('role').notNull(),
    content: text('content').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [check('messages_role_check', sql`${t.role} = ANY (ARRAY['user', 'assistant', 'teacher'])`)]
)

export const prompts = pgTable('prompts', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').notNull().references(() => authUsers.id),
  projectId: uuid('project_id').references(() => projects.id),
  content: text('content').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
})

export const lessonProgress = pgTable('lesson_progress', {
  projectId: uuid('project_id').primaryKey().references(() => projects.id),
  completedTaskIds: text('completed_task_ids').array().default([]).notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export const invoices = pgTable(
  'invoices',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id').notNull().references(() => authUsers.id),
    amountCents: integer('amount_cents').notNull(),
    description: text('description').notNull(),
    dueDate: date('due_date').notNull(),
    status: text('status').default('unpaid').notNull(),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    paidAt: timestamp('paid_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    check('invoices_amount_cents_check', sql`${t.amountCents} > 0`),
    check('invoices_status_check', sql`${t.status} = ANY (ARRAY['unpaid', 'paid', 'void'])`),
  ]
)

export const receipts = pgTable('receipts', {
  id: uuid('id').defaultRandom().primaryKey(),
  invoiceId: uuid('invoice_id').notNull().references(() => invoices.id),
  userId: uuid('user_id').notNull().references(() => authUsers.id),
  amountCents: integer('amount_cents').notNull(),
  description: text('description').notNull(),
  paidAt: timestamp('paid_at', { withTimezone: true }).notNull(),
  receiptNumber: text('receipt_number').notNull().unique(),
})

export const studentProfiles = pgTable('student_profiles', {
  userId: uuid('user_id').primaryKey().references(() => authUsers.id),
  fullName: text('full_name').default('').notNull(),
  parentEmail: text('parent_email'),
  parentTelegramChatId: text('parent_telegram_chat_id'),
  notes: text('notes'),
  isActive: boolean('is_active').default(true).notNull(),
  createdBy: uuid('created_by').references(() => authUsers.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})

export const userBuildMode = pgTable('user_build_mode', {
  userId: uuid('user_id').primaryKey().references(() => authUsers.id),
  enabled: boolean('enabled').default(false).notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export const appSettings = pgTable('app_settings', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export const roles = pgTable('roles', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull().unique(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})

export const permissions = pgTable('permissions', {
  id: uuid('id').defaultRandom().primaryKey(),
  key: text('key').notNull().unique(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})

export const rolePermissions = pgTable(
  'role_permissions',
  {
    roleId: uuid('role_id').notNull().references(() => roles.id),
    permissionId: uuid('permission_id').notNull().references(() => permissions.id),
  },
  (t) => [primaryKey({ columns: [t.roleId, t.permissionId] })]
)

export const userRoles = pgTable(
  'user_roles',
  {
    userId: uuid('user_id').notNull().references(() => authUsers.id),
    roleId: uuid('role_id').notNull().references(() => roles.id),
    grantedBy: uuid('granted_by').references(() => authUsers.id),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.roleId] })]
)
